name: 'E2E Test and Deploy'
description: 'Run Playwright e2e tests, generate report, deploy to GitHub Pages, and comment on PR'

inputs:
  base_url:
    description: 'Base URL for the application'
    required: false
    default: 'http://localhost:5173'
  test_command:
    description: 'Command to run e2e tests'
    required: false
    default: 'npm run test:e2e'
  report_path:
    description: 'Path to the test report'
    required: false
    default: 'playwright-report'

outputs:
  report_url:
    description: 'URL to the published test report'
    value: ${{ steps.report-url.outputs.report_url }}

runs:
  using: 'composite'
  steps:
    - name: Install dependencies
      shell: bash
      run: |
        if [ -f package-lock.json ]; then
          npm ci
        else
          npm install
        fi

    - name: Run e2e tests
      id: e2e-test
      shell: bash
      env:
        BASE_URL: ${{ inputs.base_url }}
      run: ${{ inputs.test_command }}

    - name: Setup Pages
      uses: actions/configure-pages@v4

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ${{ inputs.report_path }}

    - name: Deploy to GitHub Pages
      id: deploy
      uses: actions/deploy-pages@v4

    - name: Calculate report URL
      id: report-url
      shell: bash
      run: |
        REPO_FULL="${{ github.repository }}"
        OWNER=$(echo "${REPO_FULL}" | cut -d'/' -f1)
        REPO=$(echo "${REPO_FULL}" | cut -d'/' -f2)
        REPORT_URL="https://${OWNER}.github.io/${REPO}/"
        echo "report_url=${REPORT_URL}" >> $GITHUB_OUTPUT

    - name: Comment PR with report link
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          const repo = context.repo;
          const owner = repo.owner;
          const repoName = repo.repo;
          const reportUrl = `https://${owner}.github.io/${repoName}/`;
          const comment = `## 🧪 E2E Test Report\n\n📊 [View Test Report](${reportUrl})\n\n✅ Tests completed successfully!`;
          
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: owner,
            repo: repoName,
            body: comment
          });
