name: 'E2E Test and Deploy'
description: 'Run Playwright e2e tests, generate report, deploy to GitHub Pages, and comment on PR'

inputs:
  base_url:
    description: 'Base URL for the application'
    required: false
    default: 'http://localhost:5173'
  test_command:
    description: 'Command to run e2e tests'
    required: false
    default: 'npm run test:e2e'
  report_path:
    description: 'Path to the test report'
    required: false
    default: 'playwright-report'

outputs:
  test_outcome:
    description: 'Outcome of the e2e tests'
    value: ${{ steps.e2e-test.outcome }}

runs:
  using: 'composite'
  steps:
    - name: Run e2e tests
      id: e2e-test
      continue-on-error: true
      shell: bash
      env:
        BASE_URL: ${{ inputs.base_url }}
        TEST_BUILT_APP: ${{ inputs.base_url != 'http://localhost:5173' }}
      run: ${{ inputs.test_command }}
